### ISSUE TITLE
在Apache Server（HTTPD）和Tomcat在同一台电脑搭建服务器

### ISSUE THREAD

**Issue by xiaoyun94** [tencentyun/wafer#10]
之前买了一个月的腾讯云部署方案，一次要买两个服务器，感觉亏得要死
因为会话服务器（准确来说是鉴权服务器）本身已经固定，而且不需要任何修改，放在额外一个服务器，十分浪费资源。
感觉可以解决用下面的方式解决：
Apache Server负责80端口的HTTP协议，运行php的会话服务器程序
Tomcat 开启SSL，将默认的8443端口改为443端口，同时部署证书，运行java业务服务器程序
在sdk.config设置里面，将authServerUrl改为
"http://localhost/mina_auth"
（mina_auth为index.php所在文件夹名称）

**Comment by techird** [comment]
当初设计两个服务器的原因是希望会话服务和业务服务器可以分别进行伸缩。

**Comment by xiaoyun94** [comment]
那个会话服务器哪来的伸缩性一说呢？
