### ISSUE TITLE
为什么没有python语言的SDK？

### ISSUE THREAD

**Issue by CptJason** [tencentyun/wafer#15]
python作为主流开发语言，为啥没有提供相应的SDK？

**Comment by czy1996** [comment]
请问开发者有无python sdk 的开发计划，现有团队非常需要 python 语言的 sdk

**Comment by yuemeTM** [comment]
同问Python sdk计划

**Comment by techird** [comment]
目前官方团队还没有精力投入，欢迎广大开发者贡献！
