### ISSUE TITLE
请尽快出一份自行部署的教程

### ISSUE THREAD

**Issue by raypp** [tencentyun/wafer#3]
我在digitalocean上有服务器，想自己部署。还请腾讯云的同事尽快出一份wafer自行部署的教程

**Comment by techird** [comment]
好的，这个我们尽快补充！

**Comment by ochukai** [comment]
半年了~ @techird

**Comment by JianhuanZhuo** [comment]
两年了

**Comment by jas0ncn** [comment]
wafer1的可以参考：https://github.com/tencentyun/wafer/issues/8

wafer2的可以参考：https://cloud.tencent.com/document/product/619
