### ISSUE TITLE
自建服务器，信道服务器怎么配置？

### ISSUE THREAD

**Issue by JamesZhang19850319** [tencentyun/wafer#6]
如果是自建会话和业务服务器，请问能否使用腾讯云PaaS的信道服务器，信道服务器是否需要收费，如果可以，怎么配置？

**Comment by EGBAR** [comment]
@JamesZhang19850319 我遇到了与您相同的问题， 把信道服务器配置成qcloud之后，可以收到websocket连接，但是收不到来自信道服务器发来的广播消息，不知您解决了这个问题没有。

**Comment by JamesZhang19850319** [comment]
已经解决，加我扣扣1329485053

**Comment by flymysql** [comment]
我也遇到了一样的问题，想请教一下
